[package]
name = "NFTMarketplace"
version = "0.1.0"

[addresses]
NFTMarketplace = "0xb7766d073ff1b077aa8fda2859e151a621a4b8f2049685b83ab70b8b948aedba"
aptos_framework = "0x1"
primitives = "0xCAFE"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }